### ISSUE TITLE
jurplel/install-qt-action yml doesn't work

### ISSUE THREAD

**Issue by tim-gromeyer** [ddalcino/aqt-list-server#18] opened 2023-03-16 09:02 UTC
Hello,
thank you for this amazing project!
After I selected everything I need it generates me following jurpel/install-qt-action yml:
```yml
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.0'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        modules: 'qtimageformats qtmultimedia qtspeech'
```

but this doesn't work. I'll fail with following error:
```
RROR: Cannot install aqtinstall==3.1.0, aqtinstall==3.1.1, aqtinstall==3.1.2, aqtinstall==3.1.3 and py7zr==0.19.* because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested py7zr==0.19.*
    aqtinstall 3.1.3 depends on py7zr>=0.20.2
    The user requested py7zr==0.19.*
    aqtinstall 3.1.2 depends on py7zr>=0.20.2
    The user requested py7zr==0.19.*
    aqtinstall 3.1.1 depends on py7zr>=0.20.2
    The user requested py7zr==0.19.*
    aqtinstall 3.1.0 depends on py7zr>=0.20.2
```

This is because by default `jurplel/install-qt-action` uses `py7zr==0.19.*` but aqlinstall needs `py7zr>=0.20.2` or above.  
By adding `        py7zrversion: '>=0.20.2'` to the workflow the error gets fixed.

**Comment by ddalcino** [comment] 2023-03-16 14:26
Thanks for the bug report, this is worth addressing.

The root cause of this issue is tracked here: https://github.com/jurplel/install-qt-action/issues/176 . I would prefer that this problem were fixed in `install-qt-action`, because it affects everyone using the newer versions of `aqtinstall`, and ideally this project should not need to mention `py7zr` at all.

However, you are correct that this project needs to output working yml, no matter what. You’re welcome to make a PR if I don’t get to it first.

**Comment by tim-gromeyer** [comment] 2023-03-16 14:48
> The root cause of this issue is tracked here: [jurplel/install-qt-action#176](https://github.com/jurplel/install-qt-action/issues/176) . I would prefer that this problem were fixed in `install-qt-action`, because it affects everyone using the newer versions of `aqtinstall`, and ideally this project should not need to mention `py7zr` at all.

I agree with you wholeheartedly.
This should definitely fixed in `jurplel/install-qt-action`

**Closed** 2023-03-18 04:09 UTC

**Comment by ddalcino** [comment] 2023-03-18 04:41
OK, I hope #19 fixes the issue. Please let me know if there's any situation where it's still broken.
